<?php
	if(basename($_SERVER['SCRIPT_FILENAME'])=='bleach.php')
		header('location: http://www.anohanasite.altervista.org');
?>

<div id="serie_info">Ichigo Kurosaki è un giovane dotato dell'abilità di vedere gli spiriti. La sua vita subisce un drastico cambiamento quando una Shinigami (letteralmente Dio della Morte, o anche Mietitore di Anime) di nome Rukia Kuchiki, incrocia il suo cammino in cerca di un Hollow, una pericolosa anima smarrita. Durante lo scontro con lo spirito, Rukia rimane gravemente ferita ed è costretta a trasferire parte dei suoi poteri ad Ichigo, che accetta la proposta della Shinigami nel tentativo di proteggere i suoi familiari. Tuttavia, durante il processo di trasferimento, qualcosa va storto ed Ichigo assorbe tutti i poteri di Rukia, diventando uno Shinigami a pieno titolo. Avendo perso i suoi poteri, Rukia rimane bloccata nel mondo dei vivi finché non recupererà le forze. Nel frattempo, Ichigo sostituisce Rukia nei suoi doveri di Shinigami, combattendo gli Hollow e guidando le anime verso il regno dell'aldilà, noto come Soul Society (Società delle Anime).
Col passare del tempo, i superiori di Rukia vengono a sapere del trasferimento dei poteri, considerato illegale nella Soul Society, e condannano la Shinigami a morte. Nonostante non riesca ad impedire che Rukia venga riportata nella Soul Society, Ichigo si appresta a salvare la ragazza, grazie all'aiuto dei suoi compagni di classe Orihime Inoue, Uryū Ishida e Yasutora Sado e degli ex-Shinigami Yoruichi Shihōin e Kisuke Urahara. Giunti nella Soul Society, Ichigo e compagni si battono con l'élite degli Shinigami, potenziandosi nel processo, per raggiungere Rukia prima della sua esecuzione.
Sia l'esecuzione di Rukia, che il tentativo di salvataggio di Ichigo e compagni, facevano parte del piano di Sōsuke Aizen, un Capitano Shinigami, precedentemente creduto morto, che voleva entrare in possesso dell'Hougyoku, oggetto dai grandi poteri. Assieme ad altri due Capitani, Gin Ichimaru e Kaname Tōsen, Aizen tradisce i suoi compagni Shinigami e si allea con i più potenti tra gli Hollow, potenziandoli ulteriormente, proprio grazie all'Hougyoku, e tramutandoli in Arrancar.
I Capitani traditori prendono residenza nell'Hueco Mundo, la patria degli Hollow, e, grazie all'aiuto dei dieci più potenti esponenti degli Arrancar, gli Espada, rapiscono Orihime allo scopo di attirare Ichigo, i suoi alleati e alcuni degli Shinigami più potenti, lontano dalla città di Karakura, luogo dove Aizen potrà creare la Chiave del Re. Una volta in possesso della chiave, Aizen avrà accesso alla residenza del Re della Soul Society e potrà ucciderlo. A Karakura, tuttavia, i Capitani traditori, i tre Espada più potenti ed i loro sottoposti, scoprono che la città è stata sostituita con una copia e che un grande contingente di Shinigami è sul posto per sbarragli la strada.
Gli ultimi rimasti in piedi dopo lo scontro tra Shinigami ed Espada sono Aizen ed Ichigo, che nel frattempo è riuscito a tornare dall'Hueco Mundo. I due, giunti presso la vera città di Karakura, iniziano a battersi fino a quando Aizen viene sigillato grazie ad Urahara e trasportato nel Seireitei dove viene condannato a 20.000 anni di reclusione mentre Ichigo, dopo essere rimasto svenuto per un mese, ritorna alla sua vita avendo perso i poteri da Shinigami.
Diciassette mesi dopo lo scontro con Aizen, un'organizzazione formata da Fullbringer, nota come Xcution, contatta Ichigo con l'intenzione di aiutarlo a riguadagnare i suoi poteri.</div>